theme: jekyll-theme-architect
show_downloads: true
project_title: "CodeCharta"
zip_url: "https://github.com/MaibornWolff/codecharta/releases/latest"
tar_url: "https://github.com/MaibornWolff/codecharta/releases/latest"
releases_url: "https://github.com/MaibornWolff/codecharta/releases"
issues_url: "https://github.com/MaibornWolff/codecharta/issues"
