os:
  - linux

language: node_js

node_js:
  - '6'
  
sudo: required
dist: trusty

branches:
  only:
    - master
              
before_script:
  - npm install grunt-cli -g

script: ./script/travis-build.sh

cache:
  directories:
    - node_modules
    - dist/app/node_modules

notifications:
  email:
    on_success: never
    on_failure: never